name = "cf-link-shortener"
main = "src/index.js"
compatibility_date = "2024-06-20"

[[kv_namespaces]]
binding = "link-shortener"
id = "" # Replace with your KV namespace ID
preview_id = "" # Replace with your KV namespace preview ID

[vars]
# optional fallback redirect
FALLBACK_URL = ""
